### PR TITLE
Snag add

### PR DESCRIPTION
**Pull request by Sslim123**
modify the texts and links

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Write a summary of your change. Explain why you have made it.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

### CODE REVIEW

**Comment by shieldo** [comment]
This branch needs to be rebased onto the latest main branch (and the conflict resolved).

**Comment by shieldo** [comment]
There are still conflicts - it may be that the main branch needs to be synced with the upstream repository.

**Comment by Sslim123** [comment]
i solved the conflict . i will try to rebase into the lastest main branch

**Comment by shieldo** [comment]
This still contains conflicts.

I think a problem that you might be facing is having commits in your own main branch that aren't within the upstream main branch. It is probably best to keep your main only reflecting upstream changes, i.e. to not add commits to it yourself - do that in branches on your repository. Then when you sync changes from the upstream repository it will happen cleanly in a way that should mean you can correct conflicts with more confidence.

**Comment by Sslim123** [comment]
yes, sometimes i confuse a bout commit when i use terminal , but i will fix it by follow you feedback, thank you for your explanation

**Comment by Sslim123** [comment]
hi shieldo, i will merge the PR we can solve any issue if there in next PR, Because my team wait for some work from me

**Pull request merged**
